resolver 127.0.0.11 ipv6=off;

# ---------- Portail Authelia : https://auth.hotel.local ----------
server {
    listen 443 ssl;
    server_name auth.hotel.local;

    ssl_certificate     /etc/nginx/certs/cert.pem;
    ssl_certificate_key /etc/nginx/certs/key.pem;

    set $upstream_authelia_portal http://authelia:9091;

    location / {
        proxy_pass $upstream_authelia_portal;
        proxy_set_header Host $host;
        proxy_set_header X-Original-URL $scheme://$host$request_uri;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-URI $request_uri;
        proxy_set_header X-Forwarded-For $remote_addr;
    }
}

# ---------- Application protégée : https://hotel.local ----------
server {
    listen 443 ssl;
    server_name hotel.local;

    ssl_certificate     /etc/nginx/certs/cert.pem;
    ssl_certificate_key /etc/nginx/certs/key.pem;

    set $upstream_authelia http://authelia:9091/api/authz/auth-request;

    # Sous-requête interne qui demande à Authelia "cet utilisateur a le droit ou pas ?"
    location /internal/authelia/authz {
        internal;
        proxy_pass $upstream_authelia;
        proxy_set_header X-Original-Method $request_method;
        proxy_set_header X-Original-URL $scheme://$host$request_uri;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-URI $request_uri;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header Content-Length "";
        proxy_set_header Connection "";
        proxy_pass_request_body off;
    }

    location / {
        auth_request /internal/authelia/authz;
        auth_request_set $redirection_url $upstream_http_location;
        error_page 401 =302 $redirection_url;

        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }
}